#!/usr/bin/env python3
"""Install to /root/mihomo/gen_config.py — reads subscription.url (line 1), writes config.yaml."""
from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def main() -> None:
    sub_file = ROOT / "subscription.url"
    raw = sub_file.read_text(encoding="utf-8", errors="replace").strip()
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip() and not ln.strip().startswith("#")]
    if not lines:
        raise SystemExit(f"No subscription URL in {sub_file}")
    url = lines[0]
    url_yaml = json.dumps(url)

    mixed_port = int(os.environ.get("MIHOMO_MIXED_PORT", "7890"))
    ext_ctl = os.environ.get("MIHOMO_EXTERNAL_CONTROLLER", "127.0.0.1:9090").strip()

    config = f"""# Generated by gen_config.py — do not edit by hand; re-run gen_config.py after changing subscription.url
mixed-port: {mixed_port}
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: {ext_ctl}
external-ui: ""
profile:
  store-selected: true

proxy-providers:
  sub:
    type: http
    url: {url_yaml}
    interval: 3600
    path: ./providers/sub.yaml
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    lazy: false
    use:
      - sub

rules:
  - MATCH,PROXY
"""
    out = ROOT / "config.yaml"
    out.write_text(config, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
